name: PR - Dockerfile Scan

on:
  pull_request:
    paths:
      - '**/Dockerfile'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: List changed files
      id: getfile
      run: |
        files=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.before }} ${{ github.sha }})
        echo "Changed files are $files"
        echo "Changed files are $files" >> $GITHUB_ENV

    - name: Set up Docker
      run: |
        docker --version
        docker buildx create --use

    - name: Scan changed Dockerfiles
      run: |
        IFS=$'\n'
        files=(${{ env.files }})
        for file in "${files[@]}"
        do
          if [[ "$file" == *Dockerfile* ]]; then
            echo "Scanning $file..."
            image_name=$(echo $file | sed 's/\/Dockerfile//;s/\//-/g')
            docker build -t $image_name -f $file .
            trivy image --exit-code 1 $image_name
          fi
        done

