name: Build and Test Node.js App

on:
  package:
    types: [published, updated]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-nodejs-app ./images/node/test

      - name: Run Docker container
        run: docker run -d --name my-running-app -p 3000:3000 my-nodejs-app

      - name: Make CURL requests to test the app
        run: |
          sleep 5  # give some time for the app to start
          curl http://localhost:3000/healtcheck
          # Add more curl commands to test different endpoints
